ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "printFormatKey" TEXT;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "printWidthMm" INTEGER;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "printHeightMm" INTEGER;
