ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "subtitle" TEXT;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "ageRating" TEXT;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "aiGenerated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "aiGeneratedNote" TEXT;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "coAuthors" JSONB;
