-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "taxId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "payoutDocument" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bankIban" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "payoutDetailsSubmittedAt" TIMESTAMP(3);
