-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "firstName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "patronymic" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "birthDate" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "citizenship" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "registrationAddress" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "passportSeries" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "identityDocumentUrls" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "identityChangeReason" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "identityUpdatedAt" TIMESTAMP(3);
