ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "pendingTitle" TEXT;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "pendingDescription" TEXT;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "pendingGenre" TEXT;
