ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "pendingCoverUrl" TEXT;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "pendingBackCoverUrl" TEXT;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "pendingSpineUrl" TEXT;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "pendingCoverThumbUrl" TEXT;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "coverApprovedAt" TIMESTAMP(3);
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "isbnEditionSnapshot" JSONB;
