ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "udcCode" TEXT;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "bbkCode" TEXT;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "authorSign" TEXT;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "bookChamberSubmittedAt" TIMESTAMP(3);
