ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "discountPercent" INTEGER;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "discountStartsAt" TIMESTAMP(3);
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "discountEndsAt" TIMESTAMP(3);
ALTER TABLE "Book" DROP COLUMN IF EXISTS "channelPricing";
