ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "bookAuthors" JSONB;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "contributors" JSONB;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "authorBio" TEXT;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "coverIndependentFromBookData" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "desiredRoyaltyAmount" DECIMAL(10,2);
